#ifndef HTML_TEMPLATE_H
#define HTML_TEMPLATE_H

// HTML 템플릿 정의
const char* HTML_TEMPLATE = 
"HTTP/1.1 200 OK\r\n"
"Content-Type: text/html\r\n"
"\r\n"
"<!DOCTYPE html>\n"
"<html lang='ko'>\n"
"<head>\n"
"    <meta charset='UTF-8'>\n"
"    <meta name='viewport' content='width=device-width, initial-scale=1.0'>\n"
"    <title>나의 웹 서버</title>\n"
"    <style>\n"
"        body {\n"
"            font-family: 'Arial', sans-serif;\n"
"            line-height: 1.6;\n"
"            margin: 0;\n"
"            padding: 20px;\n"
"            background-color: #f0f2f5;\n"
"        }\n"
"        .container {\n"
"            max-width: 800px;\n"
"            margin: 0 auto;\n"
"            background-color: white;\n"
"            padding: 20px;\n"
"            border-radius: 10px;\n"
"            box-shadow: 0 2px 4px rgba(0,0,0,0.1);\n"
"        }\n"
"        h1 {\n"
"            color: #1a73e8;\n"
"            text-align: center;\n"
"            margin-bottom: 20px;\n"
"        }\n"
"        .info {\n"
"            background-color: #e8f0fe;\n"
"            padding: 15px;\n"
"            border-radius: 5px;\n"
"            margin-top: 20px;\n"
"        }\n"
"        .time {\n"
"            text-align: center;\n"
"            color: #666;\n"
"            margin-top: 20px;\n"
"        }\n"
"    </style>\n"
"</head>\n"
"<body>\n"
"    <div class='container'>\n"
"        <h1>환영합니다!</h1>\n"
"        <div class='info'>\n"
"            <p>이 페이지는 C로 작성된 간단한 웹 서버에서 제공됩니다.</p>\n"
"            <p>접속 정보: %s</p>\n"
"        </div>\n"
"        <div class='time'>현재 시간: %s</div>\n"
"    </div>\n"
"</body>\n"
"</html>";

#endif // HTML_TEMPLATE_H
